import {StyleSheet} from 'react-native';
import {colors, window} from '../../common';

export const styles = StyleSheet.create({
  mainCon: {
    paddingTop: window.height * 0.02,
    backgroundColor: colors.white,
    height: '100%',
  },
  scrollView: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  usernameCon: {
    width: '70%',
    justifyContent: 'center',
    height: 30,
    overflow: 'hidden',
  },
  profileImage: {
    height: 30,
    width: 30,
    borderRadius: 50,
    marginLeft: 10,
  },
  notificationsCount: {
    borderWidth: 1,
    borderColor: colors.primaryColor,
    backgroundColor: colors.red6,
    borderRadius: 10,
    height: 18,
    width: 18,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'absolute',
    top: -5,
    left: 22,
  },
  notificationCountNumber: {
    color: colors.white,
    fontSize: 10,
    fontWeight: '500',
  },
  quickAccessCon:{
    marginHorizontal: '5%',
    marginTop: '10%',
    elevation: 2,
    backgroundColor: colors.white,
    paddingHorizontal: '5%',
    paddingVertical:'3%',
    borderRadius: 5,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.3,
    shadowRadius: 2,
  },
  eachIconCon:{
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginTop: '5%',
  },
  iconstyles:{
    color: colors.black,
    // borderRadius: 5,
    // padding: 10,
    // backgroundColor: colors.gray3,
  },
  eachText:{
    textAlign: 'center',
    color: colors.black,
    fontSize: 15, 
  },
  subConOne: {
    marginTop: '10%',
    height: 'auto',
    alignItems: 'center',
    backgroundColor: colors.secondaryColor,
    marginHorizontal: window.width * 0.06,
    padding: '6%',
    paddingHorizontal: '4%',
    borderRadius: 5,
    elevation: 2,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.3,
    shadowRadius: 2,
  },
  textCon: {
    backgroundColor: colors.white,
    padding: 5,
    borderRadius: 10,
    height: '60%',
  },
  image: {
    height: 80,
    width: 170,
  },
  discoverMore: {
    fontWeight: 'bold',
    fontSize: 16,
    color: colors.black,
  },
  subConTwo: {
    height: '28%',
    marginVertical: '5%',
    alignItems: 'center',
    backgroundColor: colors.secondaryColor,
    marginHorizontal: window.width * 0.06,
    padding: '4%',
    borderRadius: 10,
    elevation: 3,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.3,
    shadowRadius: 2,
  },
  commentIcon: {
    marginRight: window.width * 0.68,
    color: colors.black,
    marginBottom: 20,
  },
  description: {
    marginHorizontal: window.width * 0.04,
    marginTop: '2%',
    marginLeft: '10%',
    color: colors.gray,
  },
  descriptionTwo: {
    marginHorizontal: window.width * 0.04,
    marginTop: '2%',
  },
  raiseRequestCon:{
    marginTop: '10%',
    marginHorizontal: '6%',
    flexDirection: 'row',
    backgroundColor: colors.secondaryColor,
    padding: '2%',
    borderRadius: 5,
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  ImageSlideCon: {
    marginTop: '10%',
    height: 180,
    marginHorizontal: window.width * 0.06,
    elevation: 5,
    borderRadius: 5,
    overflow: 'hidden',
    marginBottom:'30%'
  },
  refreshButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: '10%',
  },
  refreshText: {
    marginLeft: 5,
    color: colors.primaryColor,
    fontWeight: 'bold',
  },
  flatNameCon: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '70%',
    // backgroundColor: colors.white,
    // paddingHorizontal: '5%',
    // paddingVertical: '2%',
    alignItems: 'center',
    overflow: 'hidden',
    borderRadius: 5,
    elevation: 3,
  },
  modalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.5)',
  },
  modalContent: {
    width: '80%',
    backgroundColor: colors.white,
    padding: 20,
    borderRadius: 10,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 10,
    color: colors.black,
  },
});
